# Copyright 2026 Cloudera, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# ------- Local SSH Configuration -------

locals {
  proxied_hosts = concat(module.services.hosts, module.manager.hosts, module.sdx.hosts, module.base_masters.hosts, module.base_workers.hosts)
}

resource "local_file" "ssh_config" {
  filename = "../${var.prefix}-ssh.config"
  content  = <<EOF
# Local SSH configuration for accessing the cluster
# Generated by Terraform - do not edit manually
# Note, this configuration assumes FreeIPA enrollment on the hosts
# Use with: ssh -F <this file> <host>

# Configuration for the jump host and proxied hosts
Host jump
  HostName ${aws_eip.pvc-base[0].public_ip}
  User ${local.ami_user}
  IdentityFile ${local.private_key_file}
  UserKnownHostsFile /dev/null
  StrictHostKeyChecking no

%{ for node in local.proxied_hosts ~}
Host ${node.tags.Name} ${node.tags.Name}.cldr.internal
  HostName ${node.private_ip}
  User ${local.ami_user}
  IdentityFile ${local.private_key_file}
  ProxyJump jump
  ForwardAgent yes
  StrictHostKeyChecking no
  UserKnownHostsFile /dev/null

%{ endfor ~}
# Catch-all for raw IP addresses
Host 10.*
  User ${local.ami_user}
  IdentityFile ${local.private_key_file}
  ProxyJump jump
  ForwardAgent yes
  StrictHostKeyChecking no
  UserKnownHostsFile /dev/null
EOF
}
